# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.11.0
_src_path: gh:radio-aktywne/template-devcontainer
accountname: radio-aktywne
description: Devcontainer for MinIO databases 🦩
devcontainername: database-minio
docs: false
imagename: devcontainers/database-minio
registry: true
releases: true
reponame: devcontainer-database-minio
repourl: https://github.com/radio-aktywne/devcontainer-database-minio
